name: ttt_cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  path: 1.9.0
  propertylistserialization: 1.3.0
  xml: 6.5.0
  google_generative_ai: 0.4.6
  translator: 1.0.0
  yaml: 3.1.2
  collection: 1.18.0
  pubspec_parse: 1.2.3
  csv: 6.0.0
  xcodeproj_plus: 0.3.5
  change_case: 2.1.0
  queue: ^3.1.0+2
  analyzer: ^6.4.1
  intl: ^0.18.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
executables:
  ttt: ttt_cli